import pandas as pd
import numpy as np
df = pd.read_csv("irrigation_prediction.csv")
print("========== DATA VALIDATION ==========\n")
print("1. Dataset Shape:")
print(df.shape)
print("\n2. Column Names:")
print(df.columns.tolist())
print("\n3. Data Types:")
print(df.dtypes)
print("\n4. Missing Values:")
print(df.isnull().sum())
print("\n5. Duplicate Records:")
print(df.duplicated().sum())
print("\n6. Numerical Columns:")
print(df.select_dtypes(include=np.number).columns.tolist())
print("\n7. Categorical Columns:")
print(df.select_dtypes(include="object").columns.tolist())
print("\n8. Negative Values:")
numeric_df = df.select_dtypes(include=np.number)
print((numeric_df < 0).sum())
print("\n9. Unique Categorical Values:")
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:")
    print(df[col].unique())
print("\n10. Statistical Summary:")
print(df.describe())
print("\n========== DATA VALIDATION COMPLETED ==========")